name: RML Build

on:
  workflow_dispatch:

jobs:
  build_job:
    runs-on: ubuntu-latest
    env:
      STEAM_USERNAME: ${{ secrets.STEAMUSER }}
      STEAM_PASSWORD: ${{ secrets.STEAMPASS }}
      RESONITE_DIR: ${{ github.workspace }}/ResoniteInstall
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set Resonite Include Paths
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: >-
          <PropertyGroup Condition="'\$\(.+?\)'.+?''">(.|\n)*?<\/PropertyGroup>
        replace: >-
          <PropertyGroup><ResonitePath>$RESONITE_DIR</ResonitePath></PropertyGroup>
        include: "*.csproject"

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Install Mono
      run: sudo apt-get install -y mono-devel

    - name: Setup steamcmd
      uses: CyberAndrii/setup-steamcmd@v1

    - name: Install Resonite
      run: mkdir $RESONITE_DIR && steamcmd +@sSteamCmdForcePlatformType windows +force_install_dir $RESONITE_DIR +login $STEAM_USERNAME $STEAM_PASSWORD +app_license_request 2519830 +app_update 2519830 validate +quit
    
    - name: Download Latest RML
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "resonite-modding-group/ResoniteModLoader"
        latest: true
        fileName: "*.dll"
        out-file-path: "rmldl"

    - name: Setup RML Directories
      run: mkdir $RESONITE_DIR/rml_libs && mkdir $RESONITE_DIR/rml_mods && ls -al $RESONITE_DIR

    - name: Copy RML Files
      run: cp ./rmldl/0Harmony.dll $RESONITE_DIR/rml_libs/0Harmony.dll && cp ./rmldl/ResoniteModLoader.dll $RESONITE_DIR/Libraries/ResoniteModLoader.dll

    - name: Build
      run: dotnet build --configuration Release
    
    - name: Print Output
      run: ls -al ./bin/Release/net472